### ISSUE TITLE
Remove `run` from names of scripts

### ISSUE THREAD

**Issue by dpsanders** [WyLyu/UPOsHam#13]
It is redundant to type `run` twice, so I suggest removing `run` from the names of the scripts.

**Comment by dpsanders** [comment]
Part of JOSS review @ https://github.com/openjournals/joss-reviews/issues/1684

**Comment by Shibabrat** [comment]
@dpsanders let me know if this workflow makes sense. I'm resolving the issues that are related using pull requests and merging them as I go.

**Comment by Shibabrat** [comment]
#26 I've reopened this pull request to point out that I've addressed this issue with the names of scripts.

**Comment by dpsanders** [comment]
If you add to the description of the PR "Fixes #13" then this issue should automatically be closed when that PR is merged, and you have automatic cross-referencing.
