### ISSUE TITLE
Allow to run with no user input

### ISSUE THREAD

**Issue by dpsanders** [WyLyu/UPOsHam#14]
When I run
```
run run_diffcorr_POfam_coupled.py
``` 
I apparently need to close each figure to allow the script to proceed. (Running on MacOS if this is relevant.)

Firstly this fact should be documented, and second an option should be provided allowing the calculations to proceed without interactive figures, perhaps storing the figures somewhere instead.

**Comment by dpsanders** [comment]
Part of JOSS review @ https://github.com/openjournals/joss-reviews/issues/1684

**Comment by Shibabrat** [comment]
I've tested this issue after the PR #34 merge from the command line. The generated figures are being saved in the ./tests/plots directory. @dpsanders can you kindly double-check this and close this issue.
