### ISSUE TITLE
Use standard name for requirements file

### ISSUE THREAD

**Issue by JoshKarpel** [WyLyu/UPOsHam#15]
It looks like the requirements file got renamed to `requirements.dat` instead of `requirements.txt` in https://github.com/WyLyu/UPOsHam/commit/f643659977e6255d11f9df52a3ad3808cc549663. The `.txt` extension is standard for this file, and people will find it surprising if it isn't named that.

(Part of https://github.com/openjournals/joss-reviews/issues/1684)

**Comment by Shibabrat** [comment]
#26 I've reopened this pull request to point out the changes we have made.

**Comment by JoshKarpel** [comment]
LGTM
