### ISSUE TITLE
pip vs pip3

### ISSUE THREAD

**Issue by dpsanders** [WyLyu/UPOsHam#9]
`pip` does not exist on my system; I need to use `pip3` instead.
This should be documented in the installation instructions.

**Comment by dpsanders** [comment]
Part of JOSS review @ https://github.com/openjournals/joss-reviews/issues/1684

**Comment by JoshKarpel** [comment]
This is a fairly thorny topic; I recommend something like "using `pip` or `pip3`, whichever is appropriate for your Python installation".

**Comment by Shibabrat** [comment]
I'll make a note of this in the installation section of the readme. As an aside, I think this discussion on SO sets it straight https://stackoverflow.com/questions/40832533/pip-or-pip3-to-install-packages-for-python-3

**Comment by JoshKarpel** [comment]
I think the new installation instructions in the README resolve this. @dpsanders agreed?

**Comment by dpsanders** [comment]
Yes, agreed. 

Did I understand correctly that `python setup.py install` should automatically install the requirements? In that case, the previous line is no longer required.

**Comment by Shibabrat** [comment]
Yes, after this we will have the ```setup.py``` to check and install the requirements. Hopefully, that uses pip or pip3 depending on the system. 

I'll remove the pip instruction.
